In [1]:
import numpy as np
import pandas as pd

In [32]:
from tensorflow.keras import datasets
import warnings

warnings.filterwarnings("ignore")

datasets

<module 'keras.datasets' from 'C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\keras\\datasets\\__init__.py'>

In [33]:
(x_train,y_train),(x_test, y_test) = datasets.mnist.load_data()

In [34]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [35]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [36]:
x_train.shape

(60000, 28, 28)

In [37]:
x_test.shape

(10000, 28, 28)

In [38]:
width, height = 28,28

input_img = (width, height, 1)

In [39]:
x_train = x_train.reshape(x_train.shape[0], height, width, 1)
x_test = x_test.reshape(x_test.shape[0], height, width, 1)

In [40]:
from sklearn.model_selection import train_test_split

x_train,x_val,y_train,y_val = train_test_split(x_train,y_train, test_size = 0.2, random_state = 42)

In [41]:
#normalize the data or encoding categorical data for both x and y

x_train = (x_train - x_train.mean())/ x_train.std()
x_val = (x_val - x_val.mean()) / x_train.std()
x_test = (x_test - x_test.mean()) / x_test.std()

In [42]:
y_train

array([5, 0, 1, ..., 0, 0, 4], dtype=uint8)

In [43]:
from tensorflow.keras.utils import to_categorical

num_labels = 10

y_train = to_categorical(y_train)



In [44]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [45]:
y_val = to_categorical(y_val)
y_test = to_categorical(y_test)

In [46]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Conv2D,Input,MaxPooling2D,Flatten,AveragePooling2D

In [47]:
model = Sequential()

model.add(Conv2D(6, kernel_size = (5,5), strides = (1,1), activation = 'tanh', input_shape = (28,28,1)))
model.add(AveragePooling2D(pool_size = (2,2), strides = (1,1)))
model.add(Conv2D(16, kernel_size = (5,5), strides = (1,1), activation = 'tanh'))
model.add(AveragePooling2D(pool_size = (2,2), strides = (2,2)))
model.add(Conv2D(120, kernel_size = (5,5), strides = (1,1), activation = 'tanh'))

model.add(Flatten())
model.add(Dense(84, activation = 'tanh'))
model.add(Dense(num_labels, activation = 'softmax'))

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_3 (Conv2D)                    │ (None, 24, 24, 6)           │             156 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ average_pooling2d_2                  │ (None, 23, 23, 6)           │               0 │
│ (AveragePooling2D)                   │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_4 (Conv2D)                    │ (None, 19, 19, 16)          │           2,416 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ average_pooling2d_3                  │ (None, 9, 9, 16)            │               0 │
│ (AveragePooling2D)                   │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_5 (Conv2D)                    │ (None, 5, 5, 120)           │          48,120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_1 (Flatten)                  │ (None, 3000)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 84)                  │         252,084 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 10)                  │             850 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 303,626 (1.16 MB)

 Trainable params: 303,626 (1.16 MB)

 Non-trainable params: 0 (0.00 B)

In [48]:
from tensorflow import keras

model.compile(loss = keras.losses.categorical_crossentropy, optimizer = 'adam', metrics = ['accuracy'])

In [ ]:
history = model.fit(x_train,y_train,epochs =5, validation_data = (x_val,y_val))

Epoch 1/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 33s 17ms/step - accuracy: 0.9328 - loss: 0.2260 - val_accuracy: 0.9247 - val_loss: 0.2375
Epoch 2/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 26s 17ms/step - accuracy: 0.9697 - loss: 0.1017 - val_accuracy: 0.9663 - val_loss: 0.1106
Epoch 3/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9737 - loss: 0.0871

In [ ]:
score = model.evaluate(x_test, y_test, verbose = 1)

In [ ]:
score

In [ ]:
model.save("digit_model.h5")

In [ ]:
from tensorflow.keras.models import load_model

# Load your trained CNN model
model = load_model("digit_model.h5")


In [ ]:
import cv2
import numpy as np

# Load the image
img = cv2.imread("Documents/digit_image.jpg", cv2.IMREAD_GRAYSCALE)

# Resize to 28x28 (assuming your model was trained on MNIST-like data)
img = cv2.resize(img, (28, 28))

# Normalize pixel values
img = img / 255.0

# Reshape to match model input: (batch_size, height, width, channels)
img = img.reshape(1, 28, 28, 1)


In [ ]:
prediction = model.predict(img)
predicted_class = np.argmax(prediction)

print("Predicted Digit:", predicted_class)
